# Generated by Django 3.0.5 on 2021-01-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.IntegerField(default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('prenom', models.CharField(max_length=35)),
                ('adress', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=35)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('prenom', models.CharField(max_length=35)),
                ('adress', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField(max_length=35)),
                ('sexe', models.CharField(choices=[('1', 'M'), ('2', 'F')], max_length=1)),
                ('adrs', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=35)),
                ('tel', models.CharField(max_length=35)),
                ('mail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('0', 'Non comfirmé'), ('1', 'Inscrit'), ('2', 'Congé academique'), ('3', 'Exclus')], default='0', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libele', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('1', 'L1'), ('2', 'L2'), ('3', 'L3'), ('4', 'M1'), ('5', 'M2')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libele', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=3)),
                ('credit_requis', models.IntegerField()),
                ('coef', models.IntegerField()),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Semestre')),
            ],
            options={
                'verbose_name': 'Unité',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libele', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('coef', models.IntegerField()),
                ('charge_td', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_td', to='Scolarity.Enseignant')),
                ('charge_tp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_td', to='Scolarity.Enseignant')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Enseignant')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Unity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(choices=[('1', 'MI')], max_length=1)),
                ('nomFiliere', models.CharField(choices=[('1', 'Mathematique'), ('2', 'Informatique')], max_length=1)),
                ('niveau', models.CharField(choices=[('1', 'L1'), ('2', 'L2'), ('3', 'L3'), ('4', 'M1'), ('5', 'M2')], max_length=1)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Annee')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Groupe')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Section')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Specialite')),
            ],
        ),
        migrations.CreateModel(
            name='SuitMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cours', models.FloatField(blank=True, null=True)),
                ('note_td', models.FloatField(blank=True, null=True)),
                ('note_tp', models.FloatField(blank=True, null=True)),
                ('note_examen', models.FloatField()),
                ('session', models.CharField(choices=[('0', 'S1'), ('1', 'S2')], default=0, max_length=2)),
                ('annee', models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Annee')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarity.Matiere')),
            ],
            options={
                'verbose_name': 'Note',
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
