# Generated by Django 3.0.5 on 2021-01-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='niveau',
            field=models.CharField(choices=[('1', 'L1'), ('2', 'L2'), ('3', 'L3'), ('4', 'M1'), ('5', 'M2'), ('6', 'Phd')], max_length=1),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='niveau',
            field=models.CharField(choices=[('1', 'L1'), ('2', 'L2'), ('3', 'L3'), ('4', 'M1'), ('5', 'M2'), ('6', 'Phd')], max_length=1),
        ),
    ]
